# PumpWatchdog Bot Configuration

# Timeframes to scan (use multiple for richer prediction)
timeframes: ["1m", "5m", "15m"]

# How many candles to fetch per symbol per timeframe
max_ohlcv: 500

# Minimum 24h volume to consider (filters illiquid assets)
min_volume: 100000

# Minimum price to consider (filters out dust coins, adjust as you like)
min_price: 0.01

# Top N symbols by volume to scan
top_n: 100

# Signal score threshold to trigger alert
score_threshold: 4.0

# Required number of simultaneous indicator triggers to consider a "pump"
min_triggers: 3

# Indicator Weights (used for scoring/prediction—tune based on backtesting)
indicator_weights:
  rsi: 1.5
  stoch_rsi: 1.2
  macd: 1.4
  macd_cross: 2.0
  ema_fast: 1.0
  ema_slow: 1.0
  boll_break: 1.7
  adx: 1.2
  cci: 1.0
  williams_r: 1.0
  cmf: 1.1
  obv: 1.2
  atr: 0.8
  roc: 1.3
  volume_spike: 2.0
  donchian_break: 1.4
  keltner_break: 1.2
  trix: 1.0
  kama_trend: 1.3
  vwap_pos: 1.1

# Prediction horizon (how many candles ahead to try to predict pumps)
prediction_horizon: 3  # e.g., 3 candles ahead

# Pump expiry (how many minutes to keep reporting the same pump)
pump_expiry_minutes: 45

# Score decay per candle (to avoid repeated alerts on old pumps)
score_decay_per_candle: 0.5

# Telegram notifications
telegram:
  enabled: true
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_TELEGRAM_CHAT_ID"

# Discord notifications (optional)
discord:
  enabled: false
  webhook_url: ""

# Logging level: DEBUG, INFO, WARNING, ERROR
log_level: INFO

# Optionally add more advanced ML/threshold settings here
# e.g., min_probability: 0.7

# You may add additional keys for your scripts as needed!
